jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/accounts?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
jdbc.username=admin
jdbc.password=admin123

memcached.active.host=localhost
memcached.active.port=11211

memcached.standBy.host=localhost
memcached.standBy.port=11211

rabbitmq.address=localhost
rabbitmq.port=5672
rabbitmq.username=test
rabbitmq.password=test

elasticsearch.host=localhost
elasticsearch.port=9300
elasticsearch.cluster=vprofile
elasticsearch.node=vprofilenode
